openapi: 3.0.0
info:
  title: AI Advisor AiAdvisorDataService UserService API
  description: '# Overview

    Provides programmatic access to AI Advisor.'
  version: v202511
  contact:
    name: Kentik API Engineering
    url: https://github.com/kentik/api-schema-public
security:
- email: []
  token: []
tags:
- name: UserService
paths:
  /user/v202211/users:
    get:
      summary: List all users.
      description: Returns a list of all user accounts in the company.
      operationId: ListUsers
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v202211ListUsersResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      tags:
      - UserService
    post:
      summary: Create new user account.
      description: Creates new user account based on attributes in the request. Returns attributes of the newly created account.
      operationId: CreateUser
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v202211CreateUserResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v202211CreateUserRequest'
        required: true
      tags:
      - UserService
  /user/v202211/users/{id}:
    get:
      summary: Get attributes of a user account.
      description: Returns attributes of a user account specified by ID.
      operationId: GetUser
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v202211GetUserResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
      - name: id
        description: ID of the requested user
        in: path
        required: true
        schema:
          type: string
      tags:
      - UserService
    delete:
      summary: Delete a user account.
      description: Deletes user account specified by ID.
      operationId: DeleteUser
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v202211DeleteUserResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
      - name: id
        description: ID of the the user account to be deleted
        in: path
        required: true
        schema:
          type: string
      tags:
      - UserService
    put:
      summary: Update attributes of a user account.
      description: Replaces all attributes of a user account specified by ID with attributes in the request. Returns updated attributes.
      operationId: UpdateUser
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v202211UpdateUserResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
      - name: id
        description: System generated unique identifier
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserServiceUpdateUserBody'
        required: true
      tags:
      - UserService
  /user/v202211/users/{id}/reset_active_sessions:
    put:
      summary: Resets active sessions for a user.
      description: Resets active sessions for a user specified by ID.
      operationId: ResetActiveSessions
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v202211ResetActiveSessionsResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
      - name: id
        description: ID of the the user whose sessions should be reset
        in: path
        required: true
        schema:
          type: string
      tags:
      - UserService
  /user/v202211/users/{id}/reset_api_token:
    put:
      summary: Reset API token for a user.
      description: Resets API token for a user specified by ID.
      operationId: ResetApiToken
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v202211ResetApiTokenResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
      - name: id
        description: ID of the the user whose API token should be reset
        in: path
        required: true
        schema:
          type: string
      tags:
      - UserService
components:
  schemas:
    v202211LandingType:
      type: string
      enum:
      - LANDING_TYPE_UNSPECIFIED
      - LANDING_TYPE_LOCAL
      - LANDING_TYPE_OBSERVATION_DECK
      - LANDING_TYPE_NMS_DASHBOARD
      - LANDING_TYPE_NETWORK_EXPLORER
      - LANDING_TYPE_LIBRARY
      - LANDING_TYPE_SYNTHETICS
      - LANDING_TYPE_EXPLORER
      - LANDING_TYPE_ALERTING
      - LANDING_TYPE_INSIGHTS
      - LANDING_TYPE_DASHBOARD
      - LANDING_TYPE_SAVED_VIEW
      - LANDING_TYPE_QUICK_VIEW
      - LANDING_TYPE_MARKET_INTELLIGENCE
      default: LANDING_TYPE_UNSPECIFIED
      title: LandingType
    v202211ResetActiveSessionsResponse:
      type: object
      title: ResetActiveSessionsResponse
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
    v202211ListUsersResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/v202211User'
          description: Last of users in the account
          readOnly: true
        invalidCount:
          type: integer
          format: int64
          description: Number of invalid entries encountered while collecting data
      title: ListUsersResponse
    v202211ResetApiTokenResponse:
      type: object
      title: ResetApiTokenResponse
    UserServiceUpdateUserBody:
      type: object
      properties:
        user:
          type: object
          properties:
            userEmail:
              type: string
              description: User e-mail address (serves also as username)
            userFullName:
              type: string
              description: Full name
            role:
              $ref: '#/components/schemas/v202211Role'
            permissions:
              type: array
              items:
                $ref: '#/components/schemas/v202211PermissionEntry'
              description: Legacy permissions granted to the user (deprecated, use rbac roles and role-sets)
              readOnly: true
            filter:
              type: string
              description: Optional JSON string defining filter for objects visible to the user
            lastLogin:
              type: string
              format: date-time
              description: UTC Timestamp of user's last login session
              readOnly: true
            cdate:
              type: string
              format: date-time
              description: Creation timestamp (UTC)
              readOnly: true
            edate:
              type: string
              format: date-time
              description: Last modification timestamp (UTC)
              readOnly: true
            defaultLandingPageType:
              $ref: '#/components/schemas/v202211LandingType'
            defaultLandingPageValue:
              type: string
              description: Identifier of the specific landing page. Applies to Dashboard, Quick View, Saved View, and Observation Deck landing page types.
            roles:
              type: array
              items:
                type: string
              description: List of RBAC roles.
            roleSets:
              type: array
              items:
                type: string
              description: List of RBAC role sets.
          title: User
      title: UpdateUserRequest
      required:
      - userEmail
      - userFullName
      - role
      - user
    v202211CreateUserResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/v202211User'
      title: CreateUserResponse
    v202211Role:
      type: string
      enum:
      - ROLE_UNSPECIFIED
      - ROLE_MEMBER
      - ROLE_ADMINISTRATOR
      - ROLE_SUPER_ADMINISTRATOR
      default: ROLE_UNSPECIFIED
      description: "- ROLE_UNSPECIFIED: Invalid value.\n - ROLE_MEMBER: Member\n - ROLE_ADMINISTRATOR: Administrator\n - ROLE_SUPER_ADMINISTRATOR: Super-administrator"
      title: Role
    v202211UpdateUserResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/v202211User'
      title: UpdateUserResponse
    v202211DeleteUserResponse:
      type: object
      title: DeleteUserResponse
    v202211CreateUserRequest:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/v202211User'
      title: CreateUserRequest
      required:
      - user
    v202211User:
      type: object
      properties:
        id:
          type: string
          description: System generated unique identifier
          readOnly: true
        userEmail:
          type: string
          description: User e-mail address (serves also as username)
        userFullName:
          type: string
          description: Full name
        role:
          $ref: '#/components/schemas/v202211Role'
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/v202211PermissionEntry'
          description: Legacy permissions granted to the user (deprecated, use rbac roles and role-sets)
          readOnly: true
        filter:
          type: string
          description: Optional JSON string defining filter for objects visible to the user
        lastLogin:
          type: string
          format: date-time
          description: UTC Timestamp of user's last login session
          readOnly: true
        cdate:
          type: string
          format: date-time
          description: Creation timestamp (UTC)
          readOnly: true
        edate:
          type: string
          format: date-time
          description: Last modification timestamp (UTC)
          readOnly: true
        defaultLandingPageType:
          $ref: '#/components/schemas/v202211LandingType'
        defaultLandingPageValue:
          type: string
          description: Identifier of the specific landing page. Applies to Dashboard, Quick View, Saved View, and Observation Deck landing page types.
        roles:
          type: array
          items:
            type: string
          description: List of RBAC roles.
        roleSets:
          type: array
          items:
            type: string
          description: List of RBAC role sets.
      title: User
      required:
      - userEmail
      - userFullName
      - role
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties: {}
    v202211PermissionEntry:
      type: object
      properties:
        capability:
          type: string
          description: String identifying capability that is granted of denied
        allowed:
          type: boolean
          description: Flag indicating whether operation is allowed
      title: PermissionEntry
      required:
      - capability
      - allowed
    v202211GetUserResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/v202211User'
      title: GetUserResponse
  securitySchemes:
    email:
      type: apiKey
      name: X-CH-Auth-Email
      in: header
    token:
      type: apiKey
      name: X-CH-Auth-API-Token
      in: header
externalDocs:
  description: General information about Kentik APIs
  url: https://kb.kentik.com/v0/Ab09.htm#Ab09-APIs_Overview
